---
on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'
      - '[0-9]+.[0-9]+.[0-9]+-rc.[0-9]+'


env:
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: full

name: Build
jobs:
  build:
    name: Build contract
    # runs-on`: runs-on=${{ github.run_id }}/family=c6a.8xlarge/image=ubuntu24-full-x64/extras=s3-cache
    runs-on: ubuntu-latest
    container: rust:latest
    steps:
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Setup RunsOn
        uses: runs-on/action@v2
        with:
          metrics: cpu,network,memory,disk,io
      - name: Checkout repository
        uses: actions/checkout@v5
      - name: Install dependencies
        run: |
          apt-get update
          apt-get install -y libudev-dev
      - name: Setup Rust cache
        uses: Swatinem/rust-cache@v2
        with:
          cache-all-crates: "true"
      - name: Install dependencies
        run: cargo +stable install cargo-make cargo-near
      - name: Compile contract
        run: cargo make build

      - name: Install NPM dependencies
        working-directory: scripts/generate_abi
        run: npm ci
      - name: Generate and NPM Package
        working-directory: scripts/generate_abi
        run: npm run build

      - name: Upload contract artifacts
        uses: actions/upload-artifact@v4
        with:
          name: contracts
          path: |
            res/aurora-launchpad-factory.wasm
            target/near/aurora_launchpad_contract/aurora_launchpad_contract_abi.json

      - name: Upload NPM Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: npm-output
          path: |
            scripts/generate_abi/dist/
            scripts/generate_abi/package.json

  publish-npm:
    name: Publish NPM to GitHub Packages
    runs-on: ubuntu-latest
    needs: build
    permissions:
      contents: read
      packages: write
    steps:
      - name: Setup Node.js with GitHub Registry
        uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: 'https://npm.pkg.github.com'
          scope: '@aurora-is-near'

      - name: Download NPM Artifacts
        uses: actions/download-artifact@v4
        with:
          name: npm-output

      - name: Check files
        run: tree .

  #      - name: Publish to GitHub Packages
  #        working-directory: scripts/generate_abi
  #        run: npm publish
  #        env:
  #          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  publish:
    name: Publish contracts
    # runs-on: runs-on=${{ github.run_id }}/family=c6a.large/image=ubuntu24-full-x64
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
      - name: Publish contracts for ${{ github.ref }} release
        uses: svenstaro/upload-release-action@v2
        with:
          tag: ${{ github.ref }}
          file: "contracts/*"
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file_glob: true
