name: Tests
on:
  push:
    branches:
      - master
  pull_request:

env:
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: full

jobs:
  formatting:
    name: Code Formatting
    runs-on: runs-on=${{ github.run_id }}/family=c6a.4xlarge/image=ubuntu24-full-x64/extras=s3-cache
    container: rust:latest
    steps:
      - name: Setup RunsOn
        uses: runs-on/action@v2
      - name: Checkout repository
        uses: actions/checkout@v5
      - name: Setup Rust cache
        uses: Swatinem/rust-cache@v2
        with:
          cache-all-crates: "true"
      - name: Install dependencies
        run: cargo +stable install cargo-make
      - run: cargo make fmt

  linter:
    name: Code Linter
    runs-on: runs-on=${{ github.run_id }}/family=c6a.4xlarge/image=ubuntu24-full-x64/extras=s3-cache
    container: rust:latest
    steps:
      - name: Setup RunsOn
        uses: runs-on/action@v2
      - name: Checkout repository
        uses: actions/checkout@v5
      - name: Install dependencies
        run: |
          apt-get update
          apt-get install -y libudev-dev
      - name: Setup Rust cache
        uses: Swatinem/rust-cache@v2
        with:
          cache-all-crates: "true"
      - name: Install dependencies
        run: cargo +stable install cargo-make cargo-near
      - name: Run cargo clippy
        run: cargo make clippy

#  build:
#    name: Build contracts
#    runs-on: runs-on=${{ github.run_id }}/family=c6a.4xlarge/image=ubuntu24-full-x64/extras=s3-cache
#    container: rust:latest
#    steps:
#      - name: Setup RunsOn
#        uses: runs-on/action@v2
#      - name: Checkout repository
#        uses: actions/checkout@v5
#      - name: Install dependencies
#        run: |
#          apt-get update
#          apt-get install -y libudev-dev
#      - name: Setup Rust cache
#        uses: Swatinem/rust-cache@v2
#        with:
#          cache-all-crates: "true"
#      - name: Install dependencies
#        run: cargo +stable install cargo-make cargo-near
#      - name: Run build
#        run: cargo make build

#  tests:
#    name: Tests
#    runs-on: runs-on=${{ github.run_id }}/family=c6a.8xlarge/image=ubuntu24-full-x64/disk=large/extras=s3-cache
#    container: rust:latest
#    steps:
#      - name: Setup RunsOn
#        uses: runs-on/action@v2
#        with:
#          metrics: cpu,network,memory,disk,io
#      - name: Checkout repository
#        uses: actions/checkout@v5
#      - name: Install dependencies
#        run: |
#          apt-get update
#          apt-get install -y libudev-dev
#      - name: Setup Rust cache
#        uses: Swatinem/rust-cache@v2
#        with:
#          cache-all-crates: "true"
#      - name: Install dependencies
#        run: cargo +stable install cargo-make cargo-near cargo-nextest
#      - name: Run cargo test
#        run: cargo make test
